/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#c5c6d1",
        "surface-variant": "#dbe4ea",
        "inverse-surface": "#293236",
        "surface-tint": "#485b9a",
        "on-secondary-container": "#004666",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#304381",
        "on-secondary-fixed": "#001e2f",
        "on-primary-fixed": "#00164d",
        "primary": "#00103e",
        "error-container": "#ffdad6",
        "surface": "#f4faff",
        "background": "#f4faff",
        "surface-dim": "#d2dbe1",
        "primary-fixed": "#dce1ff",
        "on-background": "#141d21",
        "secondary": "#006591",
        "surface-container-low": "#ecf5fb",
        "on-surface-variant": "#454650",
        "primary-container": "#0c2461",
        "surface-container": "#e6eff5",
        "outline": "#757681",
        "secondary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-primary-container": "#7a8dd0",
        "surface-container-high": "#e0e9ef",
        "on-tertiary-container": "#009eb9",
        "on-secondary-fixed-variant": "#004c6e",
        "secondary-fixed-dim": "#89ceff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#e9f2f8",
        "tertiary-fixed": "#acedff",
        "surface-container-highest": "#dbe4ea",
        "on-error": "#ffffff",
        "secondary-container": "#39b8fd",
        "on-surface": "#141d21",
        "tertiary": "#00181e",
        "tertiary-container": "#002e37",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#001f26",
        "inverse-primary": "#b5c4ff",
        "primary-fixed-dim": "#b5c4ff",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-bright": "#f4faff",
        "brand-cyan": "#06b6d4",
        "brand-cyan-hover": "#0891b2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
      },
      spacing: {
        "stack-lg": "2rem",
        "margin-x": "2rem",
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        "container-max": "1280px",
        "gutter": "1.5rem",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-xl": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      boxShadow: {
        "level-1": "0 4px 6px -1px rgba(12, 36, 97, 0.1), 0 2px 4px -2px rgba(12, 36, 97, 0.06)",
        "level-2": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
